In [9]:
import papermill as pm

pm.execute_notebook(
   "test_saved_models.ipynb",
   "outputs/test_run.ipynb",
   parameters=dict(
       megadescriptor_version="B-224",
        detection="",  # '', _detected', '_detected_manual'
       query_ratio=0.2,
       seed=42
   )
)
import nbformat

nb = nbformat.read("outputs/test_run.ipynb", as_version=4)
output_cell = nb.cells[-1]

print(output_cell["outputs"][0]["data"]["text/plain"])

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

{'megadescriptor_version': 'B-224',
 'dataset_version': '',
 'seed': 42,
 'query_ratio': 0.2,
 'accuracy': 0.71875}

In [15]:
import json
import ast

with open("outputs/test_run.ipynb") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    for output in cell.get("outputs", []):
        if "text" in output:
            try:
                data = ast.literal_eval("".join(output["text"]))
                if "accuracy" in data:
                    print(data["accuracy"])
            except:
                pass

In [10]:
import numpy as np
import torch
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

SEEDS = [0, 1, 2]

DATASET_VERSIONS = [
    "",
    "_detected",
    "_detected_manual"
]

MODEL_VERSIONS = [
    'T-224','S-224', 'B-224', 'L-384'
]



results = []
i = 0
for dataset_version in DATASET_VERSIONS:
    for model_version in MODEL_VERSIONS:
        for seed in SEEDS:
            pm.execute_notebook(
                "test_saved_models.ipynb",
                f"outputs/test_run_{i}.ipynb",
                parameters=dict(
                        megadescriptor_version=model_version,
                        detection=dataset_version,
                        query_ratio=0.2,
                        seed=seed
                )
            )

            output_cell = nbformat.read(f"outputs/test_run_{i}.ipynb", as_version=4).cells[-1]
            output_text = output_cell["outputs"][0]["data"]["text/plain"]
            d = eval(output_text)
            accuracy = float(d['accuracy'])

            results.append({
                "dataset": dataset_version,
                "model": model_version,
                "seed": seed,
                "accuracy": accuracy
            })
            i += 1


df = pd.DataFrame(results)

# aggregate
summary = (
    df
    .groupby(["dataset", "model"])
    .agg(
        mean_accuracy=("accuracy", "mean"),
        std_accuracy=("accuracy", "std")
    )
    .reset_index()
)

display(summary.sort_values("mean_accuracy", ascending=False))

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

Executing:   0%|          | 0/14 [00:00<?, ?cell/s]

             dataset  model  mean_accuracy  std_accuracy
3                     T-224       0.687500      0.031250
0                     B-224       0.666667      0.047735
1                     L-384       0.656250      0.031250
2                     S-224       0.656250      0.041340
8   _detected_manual  B-224       0.650794      0.031746
5          _detected  L-384       0.641026      0.022206
11  _detected_manual  T-224       0.624339      0.039946
10  _detected_manual  S-224       0.613757      0.045821
7          _detected  T-224       0.608974      0.040032
9   _detected_manual  L-384       0.608466      0.018329
4          _detected  B-224       0.576923      0.050880
6          _detected  S-224       0.525641      0.044412

In [11]:
df

             dataset  model  seed  accuracy
0                     T-224     0  0.718750
1                     T-224     1  0.687500
2                     T-224     2  0.656250
3                     S-224     0  0.640625
4                     S-224     1  0.703125
5                     S-224     2  0.625000
6                     B-224     0  0.718750
7                     B-224     1  0.656250
8                     B-224     2  0.625000
9                     L-384     0  0.625000
10                    L-384     1  0.687500
11                    L-384     2  0.656250
12         _detected  T-224     0  0.653846
13         _detected  T-224     1  0.596154
14         _detected  T-224     2  0.576923
15         _detected  S-224     0  0.576923
16         _detected  S-224     1  0.500000
17         _detected  S-224     2  0.500000
18         _detected  B-224     0  0.634615
19         _detected  B-224     1  0.557692
20         _detected  B-224     2  0.538462
21         _detected  L-384     0  0.653846
22         _detected  L-384     1  0.653846
23         _detected  L-384     2  0.615385
24  _detected_manual  T-224     0  0.587302
25  _detected_manual  T-224     1  0.619048
26  _detected_manual  T-224     2  0.666667
27  _detected_manual  S-224     0  0.587302
28  _detected_manual  S-224     1  0.587302
29  _detected_manual  S-224     2  0.666667
30  _detected_manual  B-224     0  0.619048
31  _detected_manual  B-224     1  0.650794
32  _detected_manual  B-224     2  0.682540
33  _detected_manual  L-384     0  0.587302
34  _detected_manual  L-384     1  0.619048
35  _detected_manual  L-384     2  0.619048